apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-productapi
  labels:
    app: productapi
    version: "{{ .Chart.AppVersion }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: productapi
  template:
    metadata:
      labels:
        app: productapi
        version: "{{ .Chart.AppVersion }}"
    spec:
      containers:
      - name: productapi
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        - name: https
          containerPort: 8081
          protocol: TCP
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /api/products/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/products/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
